"use 打突ict";



 document.addEventListener('DOMContentLoaded', function() {
    const chardata = [
  // コピペ用のサンプル-------------------------------------------------------------------
  // {
  //   No: '"0000"',
  //   charimg: '"0/000/0000"',
  //   charName: '"0/000/pcl_0000.html">namesample<p>"',
  //   type: '"typesample"',
  //   class: '"classsample"',
  //   cost: '"costsample"',
  //   combo: '"combosample"',
  //   stars: '"starssample">',
  // }, 
  // コピペ用のサンプル-------------------------------------------------------------------
      {
        No: '0001',
        charimg: '0/000/0001',
        charName: '0/000/pcl_0001.html">モンキー・D・ルフィ<p>',
        type: 's">s',
        class: '格闘',
        cost: '1',
        combo: '1',
        stars: '3">',
      },
      {
        No: '0002',
        charimg: '0/000/0002',
        charName: '0/000/pcl_0002.html">モンキー・D・ルフィ<p>ゴムゴムの銃(ピストル)',
        type: 's">s',
        class: '格闘',
        cost: '4',
        combo: '4',
        stars: '4">',
      },
      {
        No: '0003',
        charimg: '0/000/0003',
        charName: '0/000/pcl_0003.html">モンキー・D・ルフィ<p>',
        type: 's">s',
        class: '格闘',
        cost: '7',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0004',
        charimg: '0/000/0004',
        charName: '0/000/pcl_0004.html">モンキー・D・ルフィ<p>',
        type: 's">s',
        class: '格闘/自由',
        cost: '15',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0005',
        charimg: '0/000/0005',
        charName: '0/000/pcl_0005.html">ロロノア・ゾロ<p>',
        type: 'd">技',
        class: '斬撃',
        cost: '4',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0006',
        charimg: '0/000/0006',
        charName: '0/000/pcl_0006.html">ロロノア・ゾロ<p>',
        type: 'd">d',
        class: '斬撃/野心',
        cost: '7',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0007',
        charimg: '0/000/0007',
        charName: '0/000/pcl_0007.html">ロロノア・ゾロ<p>',
        type: 'd">d',
        class: '斬撃/野心',
        cost: '9',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0008',
        charimg: '0/000/0008',
        charName: '0/000/pcl_0008.html">ロロノア・ゾロ<p>',
        type: 'd">d',
        class: '斬撃/野心',
        cost: '15',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0009',
        charimg: '0/000/0009',
        charName: '0/000/pcl_0009.html">ナミ<p>',
        type: 'y">知',
        class: '打突',
        cost: '4',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0010',
        charimg: '0/000/0010',
        charName: '0/000/pcl_0010.html">ナミ<p>',
        type: 'y">y',
        class: '打突/博識',
        cost: '7',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0011',
        charimg: '0/000/0011',
        charName: '0/000/pcl_0011.html">ナミ<p>',
        type: 'y">y',
        class: '打突/博識',
        cost: '9',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0012',
        charimg: '0/000/0012',
        charName: '0/000/pcl_0012.html">ナミ<p>',
        type: 'y">y',
        class: '打突/博識',
        cost: '15',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0013',
        charimg: '0/000/0013',
        charName: '0/000/pcl_0013.html">ウソップ<p>',
        type: 'p">心',
        class: '射撃',
        cost: '4',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0014',
        charimg: '0/000/0014',
        charName: '0/000/pcl_0014.html">ウソップ<p>',
        type: 'p">p',
        class: '射撃',
        cost: '7',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0015',
        charimg: '0/000/0015',
        charName: '0/000/pcl_0015.html">ウソップ<p>',
        type: 'p">p',
        class: '射撃',
        cost: '9',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0016',
        charimg: '0/000/0016',
        charName: '0/000/pcl_0016.html">ウソップ<p>',
        type: 'p">p',
        class: '射撃',
        cost: '15',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0017',
        charimg: '0/000/0017',
        charName: '0/000/pcl_0017.html">サンジ<p>',
        type: 'q">速',
        class: '格闘',
        cost: '4',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0018',
        charimg: '0/000/0018',
        charName: '0/000/pcl_0018.html">サンジ<p>',
        type: 'q">q',
        class: '格闘/強靭',
        cost: '7',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0019',
        charimg: '0/000/0019',
        charName: '0/000/pcl_0019.html">サンジ<p>',
        type: 'q">q',
        class: '格闘/強靭',
        cost: '9',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0020',
        charimg: '0/000/0020',
        charName: '0/000/pcl_0020.html">サンジ<p>',
        type: 'q">q',
        class: '格闘/強靭',
        cost: '15',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0021',
        charimg: '0/000/0021',
        charName: '0/000/pcl_0021.html">チョッパー<p>',
        type: 'p">p',
        class: '格闘',
        cost: '4',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0022',
        charimg: '0/000/0022',
        charName: '0/000/pcl_0022.html">チョッパー<p>',
        type: 'p">p',
        class: '格闘/自由',
        cost: '9',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0023',
        charimg: '0/000/0023',
        charName: '0/000/pcl_0023.html">チョッパー<p>',
        type: 'y">y',
        class: '格闘/博識',
        cost: '9',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0024',
        charimg: '0/000/0024',
        charName: '0/000/pcl_0024.html">チョッパー<p>',
        type: 's">s',
        class: '格闘/強靭',
        cost: '9',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0025',
        charimg: '0/000/0025',
        charName: '0/000/pcl_0025.html">チョッパー<p>',
        type: 'q">q',
        class: '格闘',
        cost: '9',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0026',
        charimg: '0/000/0026',
        charName: '0/000/pcl_0026.html">チョッパー<p>',
        type: 'd">d',
        class: '格闘/強靭',
        cost: '9',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0027',
        charimg: '0/000/0027',
        charName: '0/000/pcl_0027.html">ヒグマ<p>',
        type: 'q">q',
        class: '斬撃',
        cost: '8',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0028',
        charimg: '0/000/0028',
        charName: '0/000/pcl_0028.html">近海の主(ヌシ)<p>',
        type: 's">s',
        class: '格闘',
        cost: '20',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0029',
        charimg: '0/000/0029',
        charName: '0/000/pcl_0029.html">金棒のアルビダ<p>',
        type: 's">s',
        class: '打突/強靭',
        cost: '10',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0030',
        charimg: '0/000/0030',
        charName: '0/000/pcl_0030.html">金棒のアルビダ<p>(スベスベの実)',
        type: 's">s',
        class: '打突/自由',
        cost: '15',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0031',
        charimg: '0/000/0031',
        charName: '0/000/pcl_0031.html">コビー<p>',
        type: 'p">p',
        class: '格闘',
        cost: '4',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0032',
        charimg: '0/000/0032',
        charName: '0/000/pcl_0032.html">雑用コビー<p>',
        type: 'p">p',
        class: '格闘/野心',
        cost: '9',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0033',
        charimg: '0/000/0033',
        charName: '0/000/pcl_0033.html">ヘルメッポ<p>',
        type: 'y">y',
        class: '射撃',
        cost: '4',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0034',
        charimg: '0/000/0034',
        charName: '0/000/pcl_0034.html">雑用ヘルメッポ<p>',
        type: 'y">y',
        class: '格闘/野心',
        cost: '8',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0035',
        charimg: '0/000/0035',
        charName: '0/000/pcl_0035.html">斧手のモーガン<p>',
        type: 's">s',
        class: '斬撃/野心',
        cost: '9',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0036',
        charimg: '0/000/0036',
        charName: '0/000/pcl_0036.html">モージ&リッチー<p>',
        type: 'p">p',
        class: '格闘/野心',
        cost: '9',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0037',
        charimg: '0/000/0037',
        charName: '0/000/pcl_0037.html">曲芸のカバジ<p>',
        type: 'd">d',
        class: '斬撃/野心',
        cost: '9',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0038',
        charimg: '0/000/0038',
        charName: '0/000/pcl_0038.html">バギー<p>',
        type: 'y">y',
        class: '斬撃/野心',
        cost: '8',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0039',
        charimg: '0/000/0039',
        charName: '0/000/pcl_0039.html">道化のバギー<p>',
        type: 'y">y',
        class: '斬撃/野心',
        cost: '11',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0040',
        charimg: '0/000/0040',
        charName: '0/000/pcl_0040.html">ガイモン<p>',
        type: 'p">p',
        class: '射撃',
        cost: '3',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0041',
        charimg: '0/000/0041',
        charName: '0/000/pcl_0041.html">シャム<p>',
        type: 'y">y',
        class: '斬撃',
        cost: '9',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0042',
        charimg: '0/000/0042',
        charName: '0/000/pcl_0042.html">ブチ<p>',
        type: 's">s',
        class: '斬撃/強靭',
        cost: '9',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0043',
        charimg: '0/000/0043',
        charName: '0/000/pcl_0043.html">１・２のジャンゴ<p>',
        type: 'd">d',
        class: '斬撃/斬撃',
        cost: '8',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0044',
        charimg: '0/000/0044',
        charName: '0/000/pcl_0044.html">ダンシングジャンゴ<p>',
        type: 'd">d',
        class: '斬撃/斬撃',
        cost: '11',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0045',
        charimg: '0/000/0045',
        charName: '0/000/pcl_0045.html">キャプテン・クロ<p>',
        type: 'q">q',
        class: '斬撃/博識',
        cost: '10',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0046',
        charimg: '0/000/0046',
        charName: '0/000/pcl_0046.html">百計のクロ<p>',
        type: 'q">q',
        class: '斬撃/博識',
        cost: '15',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0047',
        charimg: '0/000/0047',
        charName: '0/000/pcl_0047.html">ヨサク<p>',
        type: 's">s',
        class: '斬撃',
        cost: '5',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0048',
        charimg: '0/000/0048',
        charName: '0/000/pcl_0048.html">ジョニー<p>',
        type: 'q">q',
        class: '斬撃',
        cost: '7',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0049',
        charimg: '0/000/0049',
        charName: '0/000/pcl_0049.html">namesample<p>',
        type: 's">s',
        class: '格闘',
        cost: '3',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0050',
        charimg: '0/000/0050',
        charName: '0/000/pcl_0050.html">namesample<p>',
        type: 's">s',
        class: '斬撃',
        cost: '9',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0051',
        charimg: '0/000/0051',
        charName: '0/000/pcl_0051.html">namesample<p>',
        type: 'q">q',
        class: '斬撃',
        cost: '9',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0052',
        charimg: '0/000/0052',
        charName: '0/000/pcl_0052.html">namesample<p>',
        type: 'd">d',
        class: '格闘',
        cost: '10',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0053',
        charimg: '0/000/0053',
        charName: '0/000/pcl_0053.html">namesample<p>',
        type: 'q">q',
        class: '射撃',
        cost: '8',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0054',
        charimg: '0/000/0054',
        charName: '0/000/pcl_0054.html">namesample<p>',
        type: 'q">q',
        class: '打突',
        cost: '11',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0055',
        charimg: '0/000/0055',
        charName: '0/000/pcl_0055.html">namesample<p>',
        type: 's">s',
        class: '打突/強靭',
        cost: '8',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0056',
        charimg: '0/000/0056',
        charName: '0/000/pcl_0056.html">namesample<p>',
        type: 's">s',
        class: '打突/強靭',
        cost: '11',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0057',
        charimg: '0/000/0057',
        charName: '0/000/pcl_0057.html">namesample<p>',
        type: 'y">y',
        class: '射撃/野心',
        cost: '10',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0058',
        charimg: '0/000/0058',
        charName: '0/000/pcl_0058.html">namesample<p>',
        type: 'y">y',
        class: '射撃/野心',
        cost: '15',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0059',
        charimg: '0/000/0059',
        charName: '0/000/pcl_0059.html">namesample<p>',
        type: 'y">y',
        class: '射撃/博識',
        cost: '6',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0060',
        charimg: '0/000/0060',
        charName: '0/000/pcl_0060.html">namesample<p>',
        type: 's">s',
        class: '格闘',
        cost: '18',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0061',
        charimg: '0/000/0061',
        charName: '0/000/pcl_0061.html">namesample<p>',
        type: 'y">y',
        class: '射撃/強靭',
        cost: '9',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0062',
        charimg: '0/000/0062',
        charName: '0/000/pcl_0062.html">namesample<p>',
        type: 's">s',
        class: '格闘/強靭',
        cost: '9',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0063',
        charimg: '0/000/0063',
        charName: '0/000/pcl_0063.html">namesample<p>',
        type: 'd">d',
        class: '斬撃/強靭',
        cost: '8',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0064',
        charimg: '0/000/0064',
        charName: '0/000/pcl_0064.html">namesample<p>',
        type: 'd">d',
        class: '斬撃/強靭',
        cost: '11',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0065',
        charimg: '0/000/0065',
        charName: '0/000/pcl_0065.html">namesample<p>',
        type: 's">s',
        class: '斬撃/強靭',
        cost: '10',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0066',
        charimg: '0/000/0066',
        charName: '0/000/pcl_0066.html">namesample<p>',
        type: 's">s',
        class: '斬撃/強靭',
        cost: '15',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0067',
        charimg: '0/000/0067',
        charName: '0/000/pcl_0067.html">namesample<p>',
        type: 'q">q',
        class: '斬撃/博識',
        cost: '9',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0068',
        charimg: '0/000/0068',
        charName: '0/000/pcl_0068.html">namesample<p>',
        type: 'q">q',
        class: '斬撃/博識',
        cost: '15',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0069',
        charimg: '0/000/0069',
        charName: '0/000/pcl_0069.html">namesample<p>',
        type: 'd">d',
        class: '打突/野心',
        cost: '9',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0070',
        charimg: '0/000/0070',
        charName: '0/000/pcl_0070.html">namesample<p>',
        type: 'd">d',
        class: '打突/野心',
        cost: '15',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0071',
        charimg: '0/000/0071',
        charName: '0/000/pcl_0071.html">namesample<p>',
        type: 'p">p',
        class: '斬撃',
        cost: '9',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0072',
        charimg: '0/000/0072',
        charName: '0/000/pcl_0072.html">namesample<p>',
        type: 'p">p',
        class: '斬撃',
        cost: '13',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0073',
        charimg: '0/000/0073',
        charName: '0/000/pcl_0073.html">namesample<p>',
        type: 'p">p',
        class: '斬撃/自由',
        cost: '20',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0074',
        charimg: '0/000/0074',
        charName: '0/000/pcl_0074.html">namesample<p>',
        type: 'q">q',
        class: '格闘/自由',
        cost: '20',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0075',
        charimg: '0/000/0075',
        charName: '0/000/pcl_0075.html">namesample<p>',
        type: 'q">q',
        class: '格闘/自由',
        cost: '13',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0076',
        charimg: '0/000/0076',
        charName: '0/000/pcl_0076.html">namesample<p>',
        type: 'p">p',
        class: '斬撃/博識',
        cost: '20',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0077',
        charimg: '0/000/0077',
        charName: '0/000/pcl_0077.html">namesample<p>',
        type: 'p">p',
        class: '斬撃/博識',
        cost: '20',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0078',
        charimg: '0/000/0078',
        charName: '0/000/pcl_0078.html">namesample<p>',
        type: 's">s',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0079',
        charimg: '0/000/0079',
        charName: '0/000/pcl_0079.html">namesample<p>',
        type: 'q">q',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0080',
        charimg: '0/000/0080',
        charName: '0/000/pcl_0080.html">namesample<p>',
        type: 'd">d',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0081',
        charimg: '0/000/0081',
        charName: '0/000/pcl_0081.html">namesample<p>',
        type: 'p">p',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0082',
        charimg: '0/000/0082',
        charName: '0/000/pcl_0082.html">namesample<p>',
        type: 'y">y',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0083',
        charimg: '0/000/0083',
        charName: '0/000/pcl_0083.html">namesample<p>',
        type: 'y">y',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0084',
        charimg: '0/000/0084',
        charName: '0/000/pcl_0084.html">namesample<p>',
        type: 's">s',
        class: '無',
        cost: '3',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0085',
        charimg: '0/000/0085',
        charName: '0/000/pcl_0085.html">namesample<p>',
        type: 'q">q',
        class: '無',
        cost: '3',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0086',
        charimg: '0/000/0086',
        charName: '0/000/pcl_0086.html">namesample<p>',
        type: 'd">d',
        class: '無',
        cost: '3',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0087',
        charimg: '0/000/0087',
        charName: '0/000/pcl_0087.html">namesample<p>',
        type: 'p">p',
        class: '無',
        cost: '3',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0088',
        charimg: '0/000/0088',
        charName: '0/000/pcl_0088.html">namesample<p>',
        type: 'y">y',
        class: '無',
        cost: '3',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0089',
        charimg: '0/000/0089',
        charName: '0/000/pcl_0089.html">namesample<p>',
        type: 's">s',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0090',
        charimg: '0/000/0090',
        charName: '0/000/pcl_0090.html">namesample<p>',
        type: 'q">q',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0091',
        charimg: '0/000/0091',
        charName: '0/000/pcl_0091.html">namesample<p>',
        type: 'd">d',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0092',
        charimg: '0/000/0092',
        charName: '0/000/pcl_0092.html">namesample<p>',
        type: 'p">p',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0093',
        charimg: '0/000/0093',
        charName: '0/000/pcl_0093.html">namesample<p>',
        type: 'y">y',
        class: '無',
        cost: '1',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0094',
        charimg: '0/000/0094',
        charName: '0/000/pcl_0094.html">namesample<p>',
        type: 'y">y',
        class: '無',
        cost: '3',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0095',
        charimg: '0/000/0095',
        charName: '0/000/pcl_0095.html">namesample<p>',
        type: 's">s',
        class: '無',
        cost: '2',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0096',
        charimg: '0/000/0096',
        charName: '0/000/pcl_0096.html">namesample<p>',
        type: 'q">q',
        class: '無',
        cost: '2',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0097',
        charimg: '0/000/0097',
        charName: '0/000/pcl_0097.html">namesample<p>',
        type: 'd">d',
        class: '無',
        cost: '2',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0098',
        charimg: '0/000/0098',
        charName: '0/000/pcl_0098.html">namesample<p>',
        type: 'p">p',
        class: '無',
        cost: '2',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0099',
        charimg: '0/000/0099',
        charName: '0/000/pcl_0099.html">namesample<p>',
        type: 'y">y',
        class: '無',
        cost: '2"',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0100',
        charimg: '0/100/0100',
        charName: '0/100/pcl_0100.html">namesample<p>',
        type: 's">s',
        class: '無',
        cost: '12',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0101',
        charimg: '0/100/0101',
        charName: '0/100/pcl_0101.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0102',
        charimg: '0/100/0102',
        charName: '0/100/pcl_0102.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0103',
        charimg: '0/100/0103',
        charName: '0/100/pcl_0103.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0104',
        charimg: '0/100/0104',
        charName: '0/100/pcl_0104.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0105',
        charimg: '0/100/0105',
        charName: '0/100/pcl_0105.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0106',
        charimg: '0/100/0106',
        charName: '0/100/pcl_0106.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0107',
        charimg: '0/100/0107',
        charName: '0/100/pcl_0107.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0108',
        charimg: '0/100/0108',
        charName: '0/100/pcl_0108.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0109',
        charimg: '0/100/0109',
        charName: '0/100/pcl_0109.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0110',
        charimg: '0/100/0110',
        charName: '0/100/pcl_0110.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0111',
        charimg: '0/100/0111',
        charName: '0/100/pcl_0111.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0112',
        charimg: '0/100/0112',
        charName: '0/100/pcl_0112.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0113',
        charimg: '0/100/0113',
        charName: '0/100/pcl_0113.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0114',
        charimg: '0/100/0114',
        charName: '0/100/pcl_0114.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0115',
        charimg: '0/100/0115',
        charName: '0/100/pcl_0115.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0116',
        charimg: '0/100/0116',
        charName: '0/100/pcl_0116.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0117',
        charimg: '0/100/0117',
        charName: '0/100/pcl_0117.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0118',
        charimg: '0/100/0118',
        charName: '0/100/pcl_0118.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0119',
        charimg: '0/100/0119',
        charName: '0/100/pcl_0119.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0120',
        charimg: '0/100/0120',
        charName: '0/100/pcl_0120.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0121',
        charimg: '0/100/0121',
        charName: '0/100/pcl_0121.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0122',
        charimg: '0/100/0122',
        charName: '0/100/pcl_0122.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0123',
        charimg: '0/100/0123',
        charName: '0/100/pcl_0123.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0124',
        charimg: '0/100/0124',
        charName: '0/100/pcl_0124.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0125',
        charimg: '0/100/0125',
        charName: '0/100/pcl_0125.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0126',
        charimg: '0/100/0126',
        charName: '0/100/pcl_0126.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0126',
        charimg: '0/100/0126',
        charName: '0/100/pcl_0126.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0127',
        charimg: '0/100/0127',
        charName: '0/100/pcl_0127.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0128',
        charimg: '0/100/0128',
        charName: '0/100/pcl_0128.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0129',
        charimg: '0/100/0129',
        charName: '0/100/pcl_0129.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0130',
        charimg: '0/100/0130',
        charName: '0/100/pcl_0130.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0131',
        charimg: '0/100/0131',
        charName: '0/100/pcl_0131.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0132',
        charimg: '0/100/0132',
        charName: '0/100/pcl_0132.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0133',
        charimg: '0/100/0133',
        charName: '0/100/pcl_0133.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0134',
        charimg: '0/100/0134',
        charName: '0/100/pcl_0134.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0135',
        charimg: '0/100/0135',
        charName: '0/100/pcl_0135.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0136',
        charimg: '0/100/0136',
        charName: '0/100/pcl_0136.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0137',
        charimg: '0/100/0137',
        charName: '0/100/pcl_0137.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0138',
        charimg: '0/100/0138',
        charName: '0/100/pcl_0138.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0139',
        charimg: '0/100/0139',
        charName: '0/100/pcl_0139.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0140',
        charimg: '0/100/0140',
        charName: '0/100/pcl_0140.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0141',
        charimg: '0/100/0141',
        charName: '0/100/pcl_0141.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0142',
        charimg: '0/100/0142',
        charName: '0/100/pcl_0142.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0143',
        charimg: '0/100/0143',
        charName: '0/100/pcl_0143.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0144',
        charimg: '0/100/0144',
        charName: '0/100/pcl_0144.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0145',
        charimg: '0/100/0145',
        charName: '0/100/pcl_0145.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0146',
        charimg: '0/100/0146',
        charName: '0/100/pcl_0146.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0147',
        charimg: '0/100/0147',
        charName: '0/100/pcl_0147.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0148',
        charimg: '0/100/0148',
        charName: '0/100/pcl_0148.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0149',
        charimg: '0/100/0149',
        charName: '0/100/pcl_0149.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0150',
        charimg: '0/100/0150',
        charName: '0/100/pcl_0150.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0151',
        charimg: '0/100/0151',
        charName: '0/100/pcl_0151.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0152',
        charimg: '0/100/0152',
        charName: '0/100/pcl_0152.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0153',
        charimg: '0/100/0153',
        charName: '0/100/pcl_0153.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0154',
        charimg: '0/100/0154',
        charName: '0/100/pcl_0154.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0155',
        charimg: '0/100/0155',
        charName: '0/100/pcl_0155.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0156',
        charimg: '0/100/0156',
        charName: '0/100/pcl_0156.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0157',
        charimg: '0/100/0157',
        charName: '0/100/pcl_0157.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0158',
        charimg: '0/100/0158',
        charName: '0/100/pcl_0158.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0159',
        charimg: '0/100/0159',
        charName: '0/100/pcl_0159.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0160',
        charimg: '0/100/0160',
        charName: '0/100/pcl_0160.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0161',
        charimg: '0/100/0161',
        charName: '0/100/pcl_0161.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0162',
        charimg: '0/100/0162',
        charName: '0/100/pcl_0162.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0163',
        charimg: '0/100/0163',
        charName: '0/100/pcl_0163.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0164',
        charimg: '0/100/0164',
        charName: '0/100/pcl_0164.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0165',
        charimg: '0/100/0165',
        charName: '0/100/pcl_0165.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0166',
        charimg: '0/100/0166',
        charName: '0/100/pcl_0166.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0167',
        charimg: '0/100/0167',
        charName: '0/100/pcl_0167.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0168',
        charimg: '0/100/0168',
        charName: '0/100/pcl_0168.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0169',
        charimg: '0/100/0169',
        charName: '0/100/pcl_0169.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0170',
        charimg: '0/100/0170',
        charName: '0/100/pcl_0170.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0171',
        charimg: '0/100/0171',
        charName: '0/100/pcl_0171.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0172',
        charimg: '0/100/0172',
        charName: '0/100/pcl_0172.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0173',
        charimg: '0/100/0173',
        charName: '0/100/pcl_0173.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0174',
        charimg: '0/100/0174',
        charName: '0/100/pcl_0174.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0175',
        charimg: '0/100/0175',
        charName: '0/100/pcl_0175.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0176',
        charimg: '0/100/0176',
        charName: '0/100/pcl_0176.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0177',
        charimg: '0/100/0177',
        charName: '0/100/pcl_0177.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0178',
        charimg: '0/100/0178',
        charName: '0/100/pcl_0178.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0179',
        charimg: '0/100/0179',
        charName: '0/100/pcl_0179.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0180',
        charimg: '0/100/0180',
        charName: '0/100/pcl_0180.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0181',
        charimg: '0/100/0181',
        charName: '0/100/pcl_0181.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0182',
        charimg: '0/100/0182',
        charName: '0/100/pcl_0182.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0183',
        charimg: '0/100/0183',
        charName: '0/100/pcl_0183.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0184',
        charimg: '0/100/0184',
        charName: '0/100/pcl_0184.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0185',
        charimg: '0/100/0185',
        charName: '0/100/pcl_0185.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0186',
        charimg: '0/100/0186',
        charName: '0/100/pcl_0186.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0187',
        charimg: '0/100/0187',
        charName: '0/100/pcl_0187.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0188',
        charimg: '0/100/0188',
        charName: '0/100/pcl_0188.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0189',
        charimg: '0/100/0189',
        charName: '0/100/pcl_0189.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
            {
        No: '0190',
        charimg: '0/100/0190',
        charName: '0/100/pcl_0190.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0191',
        charimg: '0/100/0191',
        charName: '0/100/pcl_0191.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0192',
        charimg: '0/100/0192',
        charName: '0/100/pcl_0192.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0193',
        charimg: '0/100/0193',
        charName: '0/100/pcl_0193.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0194',
        charimg: '0/100/0194',
        charName: '0/100/pcl_0194.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0195',
        charimg: '0/100/0195',
        charName: '0/100/pcl_0195.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0196',
        charimg: '0/100/0196',
        charName: '0/100/pcl_0196.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0197',
        charimg: '0/100/0197',
        charName: '0/100/pcl_0197.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0198',
        charimg: '0/100/0198',
        charName: '0/100/pcl_0198.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 
      {
        No: '0199',
        charimg: '0/100/0199',
        charName: '0/100/pcl_0199.html">namesample<p>',
        type: 'typesample',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: 'starssample">',
      }, 



    ];
    const container = document.getElementById('tableList');
    const table = document.createElement('table');
    const thead = document.createElement('thead');
    const tbody = document.createElement('tbody');
    table.classList.add("tableList");
    tbody.classList.add("list");

    // ヘッダーの生成
    thead.innerHTML = `
                  <tr>
                  <th class="sort" data-sort="scopeCharNo">No.</th>
                  <th data-sort="scopeCharimg">Img</th>
                  <th class="sort" data-sort="scopeCharname">名前</th>
                  <th class="sort" data-sort="scopeCharType">属性</th>
                  <th class="sort" data-sort="scopeCharClass">タイプ</th>
                  <th class="sort" data-sort="scopeCost">コスト</th>
                  <th class="sort" data-sort="scopeCombo">コンボ数</th>
                  <th data-sort="scopeStars">レアリティ</th>
              `;
    table.appendChild(thead);
    // データ行の生成
    chardata.forEach(item => {
      const tr = document.createElement('tr');
      tr.innerHTML = `
                  <td class="scopeCharNo">${item.No}</td>
                  <td class="scopeCharimg"><img src="../../img/charimgs/${item.charimg}.png" loading="lazy"></td>
                  <td class="scopeCharname"><a href="./PCL/${item.charName}</p></a></td>
                  <td class="scopeCharType type-${item.type}</td>
                  <td class="scopeCharClass class-">${item.class}</td>
                  <td class="scopeCost">${item.cost}</td>
                  <td class="scopeCombo">${item.combo}</td>
                  <td class="scopeStars stars-${item.stars}</td>
              `;
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    container.appendChild(table);


//  ---------------------------------------------------------------


/* <td class="scopeCharYpe">${item.type}</td>
<td class="scopeCharClass">${item.class}</td> */

{/* <td class="scopeCharYpe"><img src="../../img/typeimgs/${item.type}.svg" loading="lazy"></td>
<td class="scopeCharClass"><img src="../../img/classimgs/${item.class}.svg" loading="lazy"></td> */}


var options = {
  valueNames: ['scopeCharNo', 'scopeCharname', 'scopeCharType', 'scopeCharClass', 'scopeCost', 'scopeCombo', 'scopeStars'],

  page: 100,
  // ページネーション
  pagination: {
    paginationClass:'pagination',
    innerWindow:4,
    outerWindow:4,
  },
};
var tableList = new List('tableList', options);
});









// list.jsのインスタンス生成
const searchList = new List('tableList', options);
