"use strict";

 document.addEventListener('DOMContentLoaded', function() {
    const chardata = [
  // コピペ用のサンプル-------------------------------------------------------------------
  // {
  //   No: '0000',
  //   charimg: '0/000/0000',
  //   charName: '0/000/pcl_0000.html">namesample<p>',
  //   type: 'typesample',
  //   class: 'classsample',
  //   cost: 'costsample',
  //   combo: 'combosample',
  //   stars: 'starssample">',
  // }, 
  // コピペ用のサンプル-------------------------------------------------------------------
      {
        No: '0000',
        charimg: '0/000/0000',
        charName: '0/000/pcl_0000.html">このサイトの使い方<p>',
        type: 'n',
        class: 'classsample',
        cost: '999',
        combo: '999',
        stars: '6+">',
      },
      {
        No: '0001',
        charimg: '0/000/0001',
        charName: '0/000/pcl_0001.html">モンキー・D・ルフィ<p>',
        type: 's',
        class: 'classsample',
        cost: '1',
        combo: '1',
        stars: '3">',
      },
      {
        No: '0002',
        charimg: '0/000/0002',
        charName: '0/000/pcl_0002.html">モンキー・D・ルフィ<p>ゴムゴムの銃(ピストル)',
        type: 's',
        class: 'classsample',
        cost: '4',
        combo: '4',
        stars: '4">',
      },
      {
        No: '0003',
        charimg: '0/000/0003',
        charName: '0/000/pcl_0003.html">モンキー・D・ルフィ<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0004',
        charimg: '0/000/0004',
        charName: '0/000/pcl_0004.html">モンキー・D・ルフィ<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0005',
        charimg: '0/000/0005',
        charName: '0/000/pcl_0005.html">ロロノア・ゾロ<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0006',
        charimg: '0/000/0006',
        charName: '0/000/pcl_0006.html">ロロノア・ゾロ<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0007',
        charimg: '0/000/0007',
        charName: '0/000/pcl_0007.html">ロロノア・ゾロ<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0008',
        charimg: '0/000/0008',
        charName: '0/000/pcl_0008.html">ロロノア・ゾロ<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0009',
        charimg: '0/000/0009',
        charName: '0/000/pcl_0009.html">ナミ<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0010',
        charimg: '0/000/0010',
        charName: '0/000/pcl_0010.html">ナミ<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0011',
        charimg: '0/000/0011',
        charName: '0/000/pcl_0011.html">ナミ<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0012',
        charimg: '0/000/0012',
        charName: '0/000/pcl_0012.html">ナミ<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0013',
        charimg: '0/000/0013',
        charName: '0/000/pcl_0013.html">ウソップ<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0014',
        charimg: '0/000/0014',
        charName: '0/000/pcl_0014.html">ウソップ<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0015',
        charimg: '0/000/0015',
        charName: '0/000/pcl_0015.html">ウソップ<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0016',
        charimg: '0/000/0016',
        charName: '0/000/pcl_0016.html">ウソップ<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0017',
        charimg: '0/000/0017',
        charName: '0/000/pcl_0017.html">サンジ<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0018',
        charimg: '0/000/0018',
        charName: '0/000/pcl_0018.html">サンジ<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0019',
        charimg: '0/000/0019',
        charName: '0/000/pcl_0019.html">サンジ<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0020',
        charimg: '0/000/0020',
        charName: '0/000/pcl_0020.html">サンジ<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0021',
        charimg: '0/000/0021',
        charName: '0/000/pcl_0021.html">チョッパー<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0022',
        charimg: '0/000/0022',
        charName: '0/000/pcl_0022.html">チョッパー<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0023',
        charimg: '0/000/0023',
        charName: '0/000/pcl_0023.html">チョッパー<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0024',
        charimg: '0/000/0024',
        charName: '0/000/pcl_0024.html">チョッパー<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0025',
        charimg: '0/000/0025',
        charName: '0/000/pcl_0025.html">チョッパー<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0026',
        charimg: '0/000/0026',
        charName: '0/000/pcl_0026.html">チョッパー<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0027',
        charimg: '0/000/0027',
        charName: '0/000/pcl_0027.html">ヒグマ<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0028',
        charimg: '0/000/0028',
        charName: '0/000/pcl_0028.html">近海の主(ヌシ)<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0029',
        charimg: '0/000/0029',
        charName: '0/000/pcl_0029.html">金棒のアルビダ<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0030',
        charimg: '0/000/0030',
        charName: '0/000/pcl_0030.html">金棒のアルビダ<p>(スベスベの実)',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0031',
        charimg: '0/000/0031',
        charName: '0/000/pcl_0031.html">コビー<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0032',
        charimg: '0/000/0032',
        charName: '0/000/pcl_0032.html">雑用コビー<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0033',
        charimg: '0/000/0033',
        charName: '0/000/pcl_0033.html">ヘルメッポ<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0034',
        charimg: '0/000/0034',
        charName: '0/000/pcl_0034.html">雑用ヘルメッポ<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0035',
        charimg: '0/000/0035',
        charName: '0/000/pcl_0035.html">斧手のモーガン<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0036',
        charimg: '0/000/0036',
        charName: '0/000/pcl_0036.html">モージ&リッチー<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0037',
        charimg: '0/000/0037',
        charName: '0/000/pcl_0037.html">曲芸のカバジ<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0038',
        charimg: '0/000/0038',
        charName: '0/000/pcl_0038.html">バギー<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0039',
        charimg: '0/000/0039',
        charName: '0/000/pcl_0039.html">道化のバギー<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0040',
        charimg: '0/000/0040',
        charName: '0/000/pcl_0040.html">ガイモン<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0041',
        charimg: '0/000/0041',
        charName: '0/000/pcl_0041.html">シャム<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0042',
        charimg: '0/000/0042',
        charName: '0/000/pcl_0042.html">ブチ<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0043',
        charimg: '0/000/0043',
        charName: '0/000/pcl_0043.html">１・２のジャンゴ<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0044',
        charimg: '0/000/0044',
        charName: '0/000/pcl_0044.html">ダンシングジャンゴ<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0045',
        charimg: '0/000/0045',
        charName: '0/000/pcl_0045.html">キャプテン・クロ<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0046',
        charimg: '0/000/0046',
        charName: '0/000/pcl_0046.html">百計のクロ<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0047',
        charimg: '0/000/0047',
        charName: '0/000/pcl_0047.html">ヨサク<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0048',
        charimg: '0/000/0048',
        charName: '0/000/pcl_0048.html">ジョニー<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0049',
        charimg: '0/000/0049',
        charName: '0/000/pcl_0049.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0050',
        charimg: '0/000/0050',
        charName: '0/000/pcl_0050.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0051',
        charimg: '0/000/0051',
        charName: '0/000/pcl_0051.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0052',
        charimg: '0/000/0052',
        charName: '0/000/pcl_0052.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0053',
        charimg: '0/000/0053',
        charName: '0/000/pcl_0053.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0054',
        charimg: '0/000/0054',
        charName: '0/000/pcl_0054.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0055',
        charimg: '0/000/0055',
        charName: '0/000/pcl_0055.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0056',
        charimg: '0/000/0056',
        charName: '0/000/pcl_0056.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0057',
        charimg: '0/000/0057',
        charName: '0/000/pcl_0057.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0058',
        charimg: '0/000/0058',
        charName: '0/000/pcl_0058.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0059',
        charimg: '0/000/0059',
        charName: '0/000/pcl_0059.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0060',
        charimg: '0/000/0060',
        charName: '0/000/pcl_0060.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0061',
        charimg: '0/000/0061',
        charName: '0/000/pcl_0061.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0062',
        charimg: '0/000/0062',
        charName: '0/000/pcl_0062.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0063',
        charimg: '0/000/0063',
        charName: '0/000/pcl_0063.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0064',
        charimg: '0/000/0064',
        charName: '0/000/pcl_0064.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0065',
        charimg: '0/000/0065',
        charName: '0/000/pcl_0065.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0066',
        charimg: '0/000/0066',
        charName: '0/000/pcl_0066.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0067',
        charimg: '0/000/0067',
        charName: '0/000/pcl_0067.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0068',
        charimg: '0/000/0068',
        charName: '0/000/pcl_0068.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0069',
        charimg: '0/000/0069',
        charName: '0/000/pcl_0069.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0070',
        charimg: '0/000/0070',
        charName: '0/000/pcl_0070.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0071',
        charimg: '0/000/0071',
        charName: '0/000/pcl_0071.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0072',
        charimg: '0/000/0072',
        charName: '0/000/pcl_0072.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0073',
        charimg: '0/000/0073',
        charName: '0/000/pcl_0073.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0074',
        charimg: '0/000/0074',
        charName: '0/000/pcl_0074.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0075',
        charimg: '0/000/0075',
        charName: '0/000/pcl_0075.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0076',
        charimg: '0/000/0076',
        charName: '0/000/pcl_0076.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0077',
        charimg: '0/000/0077',
        charName: '0/000/pcl_0077.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0078',
        charimg: '0/000/0078',
        charName: '0/000/pcl_0078.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0079',
        charimg: '0/000/0079',
        charName: '0/000/pcl_0079.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0080',
        charimg: '0/000/0080',
        charName: '0/000/pcl_0080.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0081',
        charimg: '0/000/0081',
        charName: '0/000/pcl_0081.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0082',
        charimg: '0/000/0082',
        charName: '0/000/pcl_0082.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0083',
        charimg: '0/000/0083',
        charName: '0/000/pcl_0083.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0084',
        charimg: '0/000/0084',
        charName: '0/000/pcl_0084.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0085',
        charimg: '0/000/0085',
        charName: '0/000/pcl_0085.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0086',
        charimg: '0/000/0086',
        charName: '0/000/pcl_0086.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0087',
        charimg: '0/000/0087',
        charName: '0/000/pcl_0087.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0088',
        charimg: '0/000/0088',
        charName: '0/000/pcl_0088.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0089',
        charimg: '0/000/0089',
        charName: '0/000/pcl_0089.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0090',
        charimg: '0/000/0090',
        charName: '0/000/pcl_0090.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0091',
        charimg: '0/000/0091',
        charName: '0/000/pcl_0091.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0092',
        charimg: '0/000/0092',
        charName: '0/000/pcl_0092.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0093',
        charimg: '0/000/0093',
        charName: '0/000/pcl_0093.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0094',
        charimg: '0/000/0094',
        charName: '0/000/pcl_0094.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0095',
        charimg: '0/000/0095',
        charName: '0/000/pcl_0095.html">namesample<p>',
        type: 's',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0096',
        charimg: '0/000/0096',
        charName: '0/000/pcl_0096.html">namesample<p>',
        type: 'q',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0097',
        charimg: '0/000/0097',
        charName: '0/000/pcl_0097.html">namesample<p>',
        type: 'd',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0098',
        charimg: '0/000/0098',
        charName: '0/000/pcl_0098.html">namesample<p>',
        type: 'p',
        class: 'classsample',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0099',
        charimg: '0/000/0099',
        charName: '0/000/pcl_0099.html">namesample<p>',
        type: 'y',
        class: 'classsample',
        cost: 'costsample"',
        combo: 'combosample',
        stars: '2">',
      },
    ];
    const container = document.getElementById('tableList');
    const table = document.createElement('table');
    const thead = document.createElement('thead');
    const tbody = document.createElement('tbody');
    tbody.classList.add('list');
    table.classList.add('table');

    // ヘッダーの生成
    thead.innerHTML = `
                  <tr>
                  <th class="sort" data-sort="scopeCharNo">No.</th>
                  <th class="sort" data-sort="scopeCharimg">Img</th>
                  <th class="sort" data-sort="scopeCharname">名前</th>
                  <th class="sort" data-sort="scopeCharType">属性</th>
                  <th class="sort" data-sort="scopeCharClass">タイプ</th>
                  <th class="sort" data-sort="scopeCost">コスト</th>
                  <th class="sort" data-sort="scopeCombo">コンボ数</th>
                  <th class="sort" data-sort="scopeStars">レアリティ</th>
              `;
    table.appendChild(thead);
    // データ行の生成
    chardata.forEach(item => {
      const tr = document.createElement('tr');
      tr.innerHTML = `
                  <td class="scopeCharNo">${item.No}</td>
                  <td class="scopeCharimg"><img src="../../img/charimgs/${item.charimg}.png" loading="lazy"></td>
                  <td class="scopeCharname"><a href="./PCL/${item.charName}</p></a></td>
                  <td class="scopeCharType">${item.type}</td>
                  <td class="scopeCharClass">${item.class}</td>
                  <td class="scopeCost">${item.cost}</td>
                  <td class="scopeCombo">${item.combo}</td>
                  <td class="scopeStars scope stars-${item.stars}</td>
              `;
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    container.appendChild(table);
  });

//  ---------------------------------------------------------------


/* <td class="scopeCharType">${item.type}</td>
<td class="scopeCharClass">${item.class}</td> */

{/* <td class="scopeCharType"><img src="../../img/typeimgs/${item.type}.svg" loading="lazy"></td>
<td class="scopeCharClass"><img src="../../img/classimgs/${item.class}.svg" loading="lazy"></td> */}