"use strict";

 document.addEventListener('DOMContentLoaded', function() {
    const chardata = [
  // コピペ用のサンプル-------------------------------------------------------------------
  // {
  //   No: '0000',
  //   charimg: '0/000/0000',
  //   charName: '"0000.html">namesample<p>',
  //   typeimg: 'typesample',
  //   classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";">',
  //   cost: 'costsample',
  //   combo: 'combosample',
  //   stars: 'starssample">',
  // }, 
  // コピペ用のサンプル-------------------------------------------------------------------
      {
        No: '0000',
        charimg: '0/000/0000',
        charName: '"0000.html">Yocci<p>',
        typeimg: 'n',
        classimg: 'fr.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/dr.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: '999',
        combo: '999',
        stars: '6+">',
      },
      {
        No: '0001',
        charimg: '0/000/0001',
        charName: '"0001.html">モンキー・D・ルフィ<p>',
        typeimg: 's',
        classimg: 'fi.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: '1',
        combo: '1',
        stars: '3">',
      },
      {
        No: '0002',
        charimg: '0/000/0002',
        charName: '"0002.html">モンキー・D・ルフィ<p>ゴムゴムの銃(ピストル)',
        typeimg: 's',
        classimg: 'fi.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: '4',
        combo: '4',
        stars: '4">',
      },
      {
        No: '0003',
        charimg: '0/000/0003',
        charName: '"0003.html">モンキー・D・ルフィ<p>',
        typeimg: 's',
        classimg: 'fi.svg" loading="lazy" class="lazyload" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" class="lazyload"alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0004',
        charimg: '0/000/0004',
        charName: '"0004.html">モンキー・D・ルフィ<p>',
        typeimg: 's',
        classimg: 'fi.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/fr.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0005',
        charimg: '0/000/0005',
        charName: '"0005.html">ロロノア・ゾロ<p>',
        typeimg: 'd',
        classimg: 'sl.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/dr.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0006',
        charimg: '0/000/0006',
        charName: '"0006.html">ロロノア・ゾロ<p>',
        typeimg: 'd',
        classimg: 'sl.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/dr.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0007',
        charimg: '0/000/0007',
        charName: '"0007.html">ロロノア・ゾロ<p>',
        typeimg: 'd',
        classimg: 'st.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0008',
        charimg: '0/000/0008',
        charName: '"0008.html">ロロノア・ゾロ<p>',
        typeimg: 'd',
        classimg: 'st.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/ce.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0009',
        charimg: '0/000/0009',
        charName: '"0009.html">ナミ<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0010',
        charimg: '0/000/0010',
        charName: '"0010.html">ナミ<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0011',
        charimg: '0/000/0011',
        charName: '"0011.html">ナミ<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0012',
        charimg: '0/000/0012',
        charName: '"0012.html">ナミ<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0013',
        charimg: '0/000/0013',
        charName: '"0013.html">ウソップ<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0014',
        charimg: '0/000/0014',
        charName: '"0014.html">ウソップ<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0015',
        charimg: '0/000/0015',
        charName: '"0015.html">ウソップ<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0016',
        charimg: '0/000/0016',
        charName: '"0016.html">ウソップ<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0017',
        charimg: '0/000/0017',
        charName: '"0017.html">サンジ<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0018',
        charimg: '0/000/0018',
        charName: '"0018.html">サンジ<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0019',
        charimg: '0/000/0019',
        charName: '"0019.html">サンジ<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0020',
        charimg: '0/000/0020',
        charName: '"0020.html">サンジ<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0021',
        charimg: '0/000/0021',
        charName: '"0021.html">チョッパー<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0022',
        charimg: '0/000/0022',
        charName: '"0022.html">チョッパー<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0023',
        charimg: '0/000/0023',
        charName: '"0023.html">チョッパー<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0024',
        charimg: '0/000/0024',
        charName: '"0024.html">チョッパー<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0025',
        charimg: '0/000/0025',
        charName: '"0025.html">チョッパー<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0026',
        charimg: '0/000/0026',
        charName: '"0026.html">チョッパー<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0027',
        charimg: '0/000/0027',
        charName: '"0027.html">ヒグマ<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0028',
        charimg: '0/000/0028',
        charName: '"0028.html">近海の主(ヌシ)<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0029',
        charimg: '0/000/0029',
        charName: '"0029.html">金棒のアルビダ<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0030',
        charimg: '0/000/0030',
        charName: '"0030.html">金棒のアルビダ<p>(スベスベの実)',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0031',
        charimg: '0/000/0031',
        charName: '"0031.html">コビー<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0032',
        charimg: '0/000/0032',
        charName: '"0032.html">雑用コビー<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0033',
        charimg: '0/000/0033',
        charName: '"0033.html">ヘルメッポ<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0034',
        charimg: '0/000/0034',
        charName: '"0034.html">雑用ヘルメッポ<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0035',
        charimg: '0/000/0035',
        charName: '"0035.html">斧手のモーガン<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0036',
        charimg: '0/000/0036',
        charName: '"0036.html">モージ&リッチー<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0037',
        charimg: '0/000/0037',
        charName: '"0037.html">曲芸のカバジ<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0038',
        charimg: '0/000/0038',
        charName: '"0038.html">バギー<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0039',
        charimg: '0/000/0039',
        charName: '"0039.html">道化のバギー<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0040',
        charimg: '0/000/0040',
        charName: '"0040.html">ガイモン<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0041',
        charimg: '0/000/0041',
        charName: '"0041.html">シャム<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0042',
        charimg: '0/000/0042',
        charName: '"0042.html">ブチ<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0043',
        charimg: '0/000/0043',
        charName: '"0043.html">１・２のジャンゴ<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0044',
        charimg: '0/000/0044',
        charName: '"0044.html">ダンシングジャンゴ<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0045',
        charimg: '0/000/0045',
        charName: '"0045.html">キャプテン・クロ<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0046',
        charimg: '0/000/0046',
        charName: '"0046.html">百計のクロ<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0047',
        charimg: '0/000/0047',
        charName: '"0047.html">ヨサク<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0048',
        charimg: '0/000/0048',
        charName: '"0048.html">ジョニー<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0049',
        charimg: '0/000/0049',
        charName: '"0049.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0050',
        charimg: '0/000/0050',
        charName: '"0050.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0051',
        charimg: '0/000/0051',
        charName: '"0051.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0052',
        charimg: '0/000/0052',
        charName: '"0052.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0053',
        charimg: '0/000/0053',
        charName: '"0053.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0054',
        charimg: '0/000/0054',
        charName: '"0054.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0055',
        charimg: '0/000/0055',
        charName: '"0055.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0056',
        charimg: '0/000/0056',
        charName: '"0056.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0057',
        charimg: '0/000/0057',
        charName: '"0057.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0058',
        charimg: '0/000/0058',
        charName: '"0058.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0059',
        charimg: '0/000/0059',
        charName: '"0059.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0060',
        charimg: '0/000/0060',
        charName: '"0060.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0061',
        charimg: '0/000/0061',
        charName: '"0061.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0062',
        charimg: '0/000/0062',
        charName: '"0062.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0063',
        charimg: '0/000/0063',
        charName: '"0063.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0064',
        charimg: '0/000/0064',
        charName: '"0064.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0065',
        charimg: '0/000/0065',
        charName: '"0065.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0066',
        charimg: '0/000/0066',
        charName: '"0066.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0067',
        charimg: '0/000/0067',
        charName: '"0067.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0068',
        charimg: '0/000/0068',
        charName: '"0068.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0069',
        charimg: '0/000/0069',
        charName: '"0069.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0070',
        charimg: '0/000/0070',
        charName: '"0070.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0071',
        charimg: '0/000/0071',
        charName: '"0071.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0072',
        charimg: '0/000/0072',
        charName: '"0072.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0073',
        charimg: '0/000/0073',
        charName: '"0073.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0074',
        charimg: '0/000/0074',
        charName: '"0074.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0075',
        charimg: '0/000/0075',
        charName: '"0075.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0076',
        charimg: '0/000/0076',
        charName: '"0076.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '4">',
      },
      {
        No: '0077',
        charimg: '0/000/0077',
        charName: '"0077.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '5">',
      },
      {
        No: '0078',
        charimg: '0/000/0078',
        charName: '"0078.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0079',
        charimg: '0/000/0079',
        charName: '"0079.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0080',
        charimg: '0/000/0080',
        charName: '"0080.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0081',
        charimg: '0/000/0081',
        charName: '"0081.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0082',
        charimg: '0/000/0082',
        charName: '"0082.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0083',
        charimg: '0/000/0083',
        charName: '"0083.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '3">',
      },
      {
        No: '0084',
        charimg: '0/000/0084',
        charName: '"0084.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0085',
        charimg: '0/000/0085',
        charName: '"0085.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0086',
        charimg: '0/000/0086',
        charName: '"0086.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0087',
        charimg: '0/000/0087',
        charName: '"0087.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0088',
        charimg: '0/000/0088',
        charName: '"0088.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0089',
        charimg: '0/000/0089',
        charName: '"0089.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0090',
        charimg: '0/000/0090',
        charName: '"0090.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0091',
        charimg: '0/000/0091',
        charName: '"0091.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0092',
        charimg: '0/000/0092',
        charName: '"0092.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0093',
        charimg: '0/000/0093',
        charName: '"0093.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '1">',
      },
      {
        No: '0094',
        charimg: '0/000/0094',
        charName: '"0094.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0095',
        charimg: '0/000/0095',
        charName: '"0095.html">namesample<p>',
        typeimg: 's',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0096',
        charimg: '0/000/0096',
        charName: '"0096.html">namesample<p>',
        typeimg: 'q',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0097',
        charimg: '0/000/0097',
        charName: '"0097.html">namesample<p>',
        typeimg: 'd',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0098',
        charimg: '0/000/0098',
        charName: '"0098.html">namesample<p>',
        typeimg: 'p',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample',
        combo: 'combosample',
        stars: '2">',
      },
      {
        No: '0099',
        charimg: '0/000/0099',
        charName: '"0099.html">namesample<p>',
        typeimg: 'y',
        classimg: 'classsample.svg" loading="lazy" class="lazyload"><img data-src="../../img/classimgs/classsample.svg" loading="lazy" class="lazyload" alt onerror="this.onerror = null; this.data-src="";"',
        cost: 'costsample class="lazyload"',
        combo: 'combosample',
        stars: '2">',
      },
    ];
    const container = document.getElementById('tableList');
    const table = document.createElement('table');
    const thead = document.createElement('thead');
    const tbody = document.createElement('tbody');
    tbody.classList.add('list');
    table.classList.add('table');

    // ヘッダーの生成
    thead.innerHTML = `
                  <tr>
                  <th class="sort" data-sort="scopeCharNo">No.</th>
                  <th class="sort" data-sort="scopeCharimg">Img</th>
                  <th class="sort" data-sort="scopeCharname">名前</th>
                  <th class="sort" data-sort="scopeTypeimg">属性</th>
                  <th class="sort" data-sort="scopeClassimg">タイプ</th>
                  <th class="sort" data-sort="scopeCost">コスト</th>
                  <th class="sort" data-sort="scopeCombo">コンボ数</th>
                  <th class="sort" data-sort="scopeStars">レアリティ</th>
              `;
    table.appendChild(thead);
    // データ行の生成
    chardata.forEach(item => {
      const tr = document.createElement('tr');
      tr.innerHTML = `
                  <td class="scopeCharNo">${item.No}</td>
                  <td class="scopeCharimg lazyload"><img data-src="../../img/charimgs/${item.charimg}.png" loading="lazy" class="lazyload"></td>
                  <td class="scopeCharname"><a href="./PCL/${item.charName}</p></a></td>
                  <td class="scopeTypeimg lazyload"><img data-src="../../img/typeimgs/${item.typeimg}.svg" loading="lazy" class="lazyload"></td>
                  <td class="scopeClassimg lazyload"><img data-src="../../img/classimgs/${item.classimg}</td>
                  <td class="scopeCost">${item.cost}</td>
                  <td class="scopeCombo">${item.combo}</td>
                  <td class="scopeStars scope stars-${item.stars}</td>
              `;
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    container.appendChild(table);
  });

//  ---------------------------------------------------------------
